<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Knp\DoctrineBehaviors\ORM as ORMBehaviors;
use UserBundle\Entity\User;

/**
 * DirectoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function getRootDirectories(User $user)
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('d')
            ->from('AppBundle:Directory', 'd')
            ->where('d.user = ?1 AND d.directory IS NULL')
            ->setParameter(1, $user->getId());

        $query = $queryBuilder->getQuery();
        unset($queryBuilder);
        return $query->getResult();
    }

}
