<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Knp\DoctrineBehaviors\ORM as ORMBehaviors;

/**
 * DirectoryRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class DirectoryRepository extends EntityRepository
{
    use ORMBehaviors\Tree\Tree;
}
