<?php
namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FileRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class FileRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function getRootFiles()
    {
        $em = $this->getEntityManager();
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('f')
            ->from('AppBundle:File', 'f')
            ->where('f.directory IS NULL');

        $query = $queryBuilder->getQuery();
        unset($queryBuilder);
        return $query->getResult();
    }

}
